### PR TITLE
Stop IndexOutOfRangeException when applying patches which make files empty

### PR DESCRIPTION
**Pull request by tomcsmith1990**
This makes it possible to apply a patch which makes a file empty.

This is needed for MigrationBlocks because when we create the migration script, there may be empty files in the working base (which are there because Compare makes files empty rather than deleting them).

I may have missed other cases as I haven't dug into the implementation very deeply, but the test passes which I think is all I need.

### CODE REVIEW

**Comment by nyctef** [comment]
> (which are there because Compare makes files empty rather than deleting them).

This behaviour seems to have come up a few times recently. Is it worth looking at if we can fix it? I don't think there's a good reason not to delete files any more

**Comment by tomcsmith1990** [comment]
It would be nice to fix, but this is a much smaller fix for what we need right now (and also it does seem like it's a genuine bug in NGit so should be fixed).

**Comment by nyctef** [comment]
Yep, no worries for now :)

**Comment by GrahamTheCoder** [comment]
Yeah we need this bug fix for other reasons anyway, but for the general compare thing I think we should do something like:
- Make SOC agnostic to whether the file is deleted or empty
  - Delete any empty schema files as they come into Engine.Diff from Compare (so SOCO isn't screwed by this)
  - Make TFS recreate the file as empty if it needs it
- Make Compare delete files rather than making them empty

**Pull request merged**
